behaviors:
  SmartFlappyBirdPPO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 50000
      learning_rate: 0.0003
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 100000
    max_steps: 1000000
    time_horizon: 32
    summary_freq: 10000
    threaded: true
